// <auto-generated />
using BancoHoras.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BancoHoras.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231130191955_v2")]
    partial class v2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("BancoHoras.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("InicioManha")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FimManha")
                    .IsRequired()
                    .HasColumnType("TEXT");

                    b.Property<string>("InicioTarde")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FimTarde")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TempoTotal")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacoes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });
#pragma warning restore 612, 618
        }
    }
}
